version: "3.7"

services:

  front-envoy:
    build:
      context: .
      dockerfile: .docker/envoy/Dockerfile
    networks:
      - envoymesh
    ports:
      - "8080:8080" # http
      - "8443:8443" # https
      - "8001:8001" # admin

  hp-api:
    build:
      context: .
      dockerfile: .docker/service/Dockerfile
    volumes:
      - .envoy/service-envoy.yaml:/etc/service-envoy.yaml
    networks:
      - envoymesh
    environment:
      - SERVICE_NAME=1

networks:
  envoymesh: {}
